!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

 default_basis_path = '/home/ymbyun/programs/molgw-1.F-2019.03.20-N17.O1-GW.inner-time/basis/' 

